// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVbZ2aUOcxd_d5dGywrChi7ntyFOxaYY',
    appId: '1:118957275641:android:f6f59c4e388f33c6282528',
    messagingSenderId: '118957275641',
    projectId: 'airforce-92b59',
    storageBucket: 'airforce-92b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0BkHfdeWH70zDPaDT8gYbYO4S0rqJuns',
    appId: '1:118957275641:ios:727da23c341e1901282528',
    messagingSenderId: '118957275641',
    projectId: 'airforce-92b59',
    storageBucket: 'airforce-92b59.firebasestorage.app',
    androidClientId: '118957275641-mcm26lmflsuh5jo8npnhdcp0fbsprn7j.apps.googleusercontent.com',
    iosClientId: '118957275641-du6qbi3misd7429e2l8g3u6dhk8jc2j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rokafirst',
  );
}
